verbose: True
show_progress: False
show_images: True
make_movie: True

no_in_absorption: False
no_out_absorption: False
#~ no_in_absorption: True
#~ no_out_absorption: True

backprojector: 'fbp'    # one of 'fbp', 'sart_no_prior'

anglesfile: 'angles.txt'
