---
verbose: True
show_progress: False
show_images: True
make_movie: True

no_in_absorption: False
no_out_absorption: False
#~ no_in_absorption: True
#~ no_out_absorption: True

#~ iradon_implementation: 'skimage_iradon'
iradon_implementation: 'xlict_recon_mpi_fbp'
#~ iradon_implementation: 'xlict_recon_gridrec'
#~ iradon_implementation: 'skimage_iradon_sart'
# one of 'skimage_iradon', 'skimage_iradon_sart', 'xlict_recon_mpi_fbp'
skimage_iradon_circle: True
skimage_iradon_filter: null
backprojector: 'fbp'    # one of 'fbp', 'sart_no_prior'

xlict_recon_mpi_corm: 0.0
xlict_force_cpu: 0
xlict_recon_mpi_exe: 'R:\Science\XFM\GaryRuben\software_to_keep\XLICTReconMPI\XLICTReconMPI.exe'
xlict_recon_mpi_fbp_PATH_INPUT_TIFFS: 'R:\Science\XFM\GaryRuben\figures_for_posters_and_presentations\ricegrain'
xlict_recon_mpi_fbp_PATH_OUTPUT_DATA: 'C:\Users\rub015\Desktop\ricegrain_out'
xlict_recon_mpi_fbp_filter: 'none'
#~ xlict_recon_mpi_fbp_filter: 'shepp-logan'
# One of 'ramp', 'shepp-logan', 'cosine', 'hamming', 'hann', 'none'

anglesfile: 'angles.txt'

energy_keV: 15.6

# input model
map_pattern: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom3-*.tiff'
map_elements: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom3.yaml'
map_width_um: 2000.0
#~ map_pattern: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom4-*.tiff'
#~ map_elements: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom4.yaml'
#~ map_width_um: 1990.0

#---
#Uncomment this section to use the Maia detector
#detector_csv: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Maia_384C.csv'
#detector_pads: [341]    # 7, 7
#---
#Uncomment this section to use a single square pad
detector_csv: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\pseudo_maia_as_one_square_pad.csv'
detector_pads: [1]
#---