---
verbose: True
show_progress: True
save_f_images: True
save_d_images: False
save_g_images: False
save_projection_images: True
make_movie: True

no_in_absorption: False
no_out_absorption: False
#no_in_absorption: True
#no_out_absorption: True

#iradon_implementation: 'skimage_iradon'
iradon_implementation: 'xlict_recon_mpi_fbp'
# iradon_implementation: 'xlict_recon_gridrec'
# one of 'skimage_iradon', 'skimage_iradon_sart', 'xlict_recon_mpi_fbp'
skimage_iradon_circle: True
skimage_iradon_filter: null
backprojector: 'fbp'    # one of 'fbp', 'sart_no_prior'

logger_path: 'C:\temp\mlem_ims\log.log'
logger_level: logging.INFO
mlem_im_path: 'C:\temp\mlem_ims'
mlem_reference_image_path: 'R:\Science\XFM\GaryRuben\projects\TMM\work\20160502_3\Grain_test_phantom1-Zn.tiff'
mlem_mse_path: 'C:\temp\mlem_ims\mse.txt'
mlem_mssim_path: 'C:\temp\mlem_ims\mssim.txt'
mlem_save_similarity_metrics: True
mlem_transpose_on_read: True
matrix_blur: False
absorb_with_matrix_only: True

xlict_recon_mpi_corm: 0.0
xlict_force_cpu: 0
xlict_recon_mpi_exe: 'R:\Science\XFM\GaryRuben\software_to_keep\XLICTReconMPI\XLICTReconMPI.exe'
xlict_recon_mpi_fbp_PATH_INPUT_TIFFS: 'R:\Science\XFM\GaryRuben\projects\ricegrain_recon'
xlict_recon_mpi_fbp_PATH_OUTPUT_DATA: 'C:\Users\rub015\Desktop\ricegrain_out'
xlict_recon_mpi_fbp_filter: 'none'
#~ xlict_recon_mpi_fbp_filter: 'shepp-logan'
# One of 'ramp', 'shepp-logan', 'cosine', 'hamming', 'hann', 'none'

#anglesfile: 'angles.txt'
angles_compute: True
angles_closed_range: False
angles_max: 360.0

energy_keV: 14.5
#energy_keV: 15.6
element: Zn
#element: Ni

# input model 200x200px of the simulated test phantom. See readme.txt in
# R:\Science\XFM\GaryRuben\projects\TMM\work\20160405_1:
map_pattern: 'R:\Science\XFM\GaryRuben\projects\TMM\work\20160503_1\Grain_test_phantom1-*.tiff'
map_elements: 'R:\Science\XFM\GaryRuben\projects\TMM\work\20160422_1\Grain_test_phantom1.yaml'
map_width_um: 4000.0

# input model 200x200px of the simulated test phantom. See readme.txt in
# R:\Science\XFM\GaryRuben\projects\TMM\work\20160405_1:
#map_pattern: 'R:\Science\XFM\GaryRuben\projects\TMM\work\20160405_1\Ni_test_phantom4-*.tiff'
#map_elements: 'R:\Science\XFM\GaryRuben\projects\TMM\work\20160405_1\Ni_test_phantom4.yaml'
#map_width_um: 4000.0

# input model 200x200px:
#map_pattern: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom3-*.tiff'
#map_elements: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom3.yaml'
#map_width_um: 2000.0

#map_pattern: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom4-*.tiff'
#map_elements: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom4.yaml'
#map_width_um: 1990.0

# 1000x1000px:
#map_pattern: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom5-*.tiff'
#map_elements: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Ni_test_phantom5.yaml'
#map_width_um: 2000.0

#map_pattern: 'R:\Science\XFM\GaryRuben\projects\ricegrain_recon\Ricegrain_sino-*.tif'
#map_elements: 'R:\Science\XFM\GaryRuben\projects\ricegrain_recon\Ricegrain_with_Zn.yaml'
# According to values in Rice_Ge2Hhires_726.xls, dx=dy=2um and x-ax-s extent = 4.6mm
#map_width_um: 4600.0
slice_thickness_um: 2.0
# For density_per_compton_count see work/20160222_1/Absorption_from_Ge_sinogram-rescaled_image.ipynb
#density_per_compton_count: 0.0001038   # matrix density for ricegrain

#density_per_compton_count: 4.25e-2      # matrix density for Ni_test_phantom2
#density_per_compton_count: 15.0e-2      # matrix density for Ni_test_phantom2
#density_per_compton_count: 7.0e-2      # matrix density for Ni_test_phantom2
#density_per_compton_count: 0.1      # matrix density for Ni_test_phantom2
density_per_compton_count: 5.0e-2      # matrix density for Ni_test_phantom2

#---
#Uncomment this section to use the Maia detector
detector_csv: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\Maia_384C.csv'
detector_pads: [341]    # 7, 7
#---
#Uncomment this section to use a single square pad
#detector_csv: 'R:\Science\XFM\GaryRuben\git_repos\tmm_model\acsemble\data\pseudo_maia_as_one_square_pad.csv'
#detector_pads: [1]
#---